language: haskell
ghc:
  - 7.8
node_js:
  - 0.10
branches:
  except:
    - old
    - ancient
install:
  - make bower_components
  - cabal install purescript
script: make test
notifications:
  irc: "irc.freenode.org#kh6e"
