bower:
  files:
  - cwd: bower_components/L.GeoSearch/src/
    src:
     - "**"
    dest: dist/assets/L.GeoSearch/
    expand: true
  - cwd: bower_components/Leaflet.awesome-markers/dist/
    src:
    - "**"
    dest: dist/assets/Leaflet.awesome-markers/
    expand: true
  - cwd: bower_components/bootstrap/dist/
    src:
    - "fonts/**"
    - "js/**"
    dest: dist/assets/bootstrap/
    expand: true
  - cwd: bower_components/font-awesome/
    src:
    - "**/*.{css,eot,js,map,svg,ttf,woff}"
    dest: dist/assets/font-awesome/
    expand: true
  - cwd: bower_components/html5shiv/dist/
    src:
    - "**"
    dest: dist/assets/html5shiv/
    expand: true
  - cwd: bower_components/jquery/dist/
    src:
    - "**"
    dest: dist/assets/jquery/
    expand: true
  - cwd: bower_components/leaflet/dist/
    src:
    - "**"
    dest: dist/assets/leaflet/
    expand: true

data:
  src:
  - "data/**/*.json"
  dest: dist/assets/
  expand: true

site:
  src:
  - "js/**"
  - "img/**"
  - "doc/**"
  dest: dist/assets/
  expand: true
