styles:
  files:
    dist/assets/css/bootstrap.css:
    - "less/bootstrap.less"
    dist/assets/css/default.css:
    - "less/default.less"
    dist/assets/css/index.css:
    - "less/index.less"
    dist/assets/css/map.css:
    - "less/map.less"
