styles:
  files:
    dist/assets/bootstrap/css/bootstrap.css:
    - "bower_components/bootstrap/less/bootstrap.less"
    - "less/variables.less"
    dist/assets/css/site.css:
    - "less/body.less"
    - "less/bootstrap.less"
    - "less/footer.less"
    - "less/header.less"
    - "less/heading.less"
    - "less/map.less"
    - "less/nav.less"
    - "less/table.less"
